Source/Boxed.AspNetCore.Swagger/FilterDescriptorExtensions.cs, Source/Boxed.AspNetCore.Swagger/SwaggerGenOptionsExtensions.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphBooksBook.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphBusiness.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphFitnessCourse.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphProduct.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphProductItem.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphRestaurant.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphRestaurantMenu.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphRestaurantMenuItem.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphRestaurantMenuSection.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/OpenGraphMetadata.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Standard/OpenGraphVideoEpisode.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Standard/OpenGraphVideoMovie.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Standard/OpenGraphVideoOther.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Standard/OpenGraphVideoTvShow.cs, Source/Boxed.AspNetCore.TagHelpers/StringBuilderExtensions.cs, Source/Boxed.AspNetCore.TagHelpers/Twitter/Cards/TwitterCardSummary.cs, Source/Boxed.AspNetCore.TagHelpers/Twitter/Cards/TwitterCardSummaryLargeImage.cs, Source/Boxed.AspNetCore/HttpRequestExtensions.cs, Source/Boxed.AspNetCore/RedirectToCanonicalUrlRule.cs, Source/Boxed.DotnetNewTest/AssemblyResolver.cs, Source/Boxed.DotnetNewTest/DotnetNew.cs, Source/Boxed.DotnetNewTest/ProcessExtensions.StartAsync.cs, Source/Boxed.DotnetNewTest/TempDirectoryExtensions.cs, build.cake
=> Replace '!= null' with 'is object'

Framework.sln, Source/Boxed.AspNetCore.Swagger/Boxed.AspNetCore.Swagger.csproj, Source/Boxed.AspNetCore.TagHelpers/Boxed.AspNetCore.TagHelpers.csproj, Source/Boxed.AspNetCore/Boxed.AspNetCore.csproj, Source/Boxed.DotnetNewTest/Boxed.DotnetNewTest.csproj, Source/Boxed.Mapping/Boxed.Mapping.csproj, Source/Directory.Build.props, Tests/Boxed.AspNetCore.Swagger.Test/Boxed.AspNetCore.Swagger.Test.csproj, Tests/Boxed.AspNetCore.TagHelpers.Test/Boxed.AspNetCore.TagHelpers.Test.csproj, Tests/Boxed.AspNetCore.Test/Boxed.AspNetCore.Test.csproj, Tests/Boxed.Mapping.Test/Boxed.Mapping.Test.csproj, Tests/Directory.Build.props
=> Add Multiple nested Directory.Build.props

Source/Boxed.DotnetNewTest/TempDirectoryExtensions.cs
https://github.com/Dotnet-Boxed/Framework/issues/176
=> Make name optional in DotnetNewAsync

Source/Boxed.Mapping/AsyncMapperExtensions.cs, Source/Boxed.Mapping/Boxed.Mapping.csproj, Source/Boxed.Mapping/IAsyncMapper.cs, Tests/Boxed.Mapping.Test/AsyncMapper.cs, Tests/Boxed.Mapping.Test/AsyncMapperTest.cs, Tests/Boxed.Mapping.Test/Disposable.cs
=> Add CancellationToken to async mapper

Directory.Build.props, Source/Boxed.AspNetCore.TagHelpers/SubresourceIntegrityTagHelper.cs, Source/Boxed.AspNetCore/Middleware/HttpExceptionMiddlewareOptions.cs
=> Bump Microsoft.CodeAnalysis.FxCopAnalyzers from 3.0.0 to 3.3.0

.github/workflows/build.yml, Source/Boxed.DotnetNewTest/ConfigurationService.cs, Source/Boxed.DotnetNewTest/DotnetNew.cs, Source/Boxed.DotnetNewTest/ProjectExtensions.cs, Source/Boxed.DotnetNewTest/TempDirectoryExtensions.cs
=> Add Default Timeout to DotnetNew

README.md, Source/Boxed.Mapping/AsyncImmutableMapperExtensions.cs, Source/Boxed.Mapping/IAsyncImmutableMapper.cs, Source/Boxed.Mapping/IImmutableMapper.cs, Source/Boxed.Mapping/ImmutableMapperExtensions.cs, Tests/Boxed.Mapping.Test/AsyncImmutableMapper.cs, Tests/Boxed.Mapping.Test/AsyncImmutableMapperTest.cs, Tests/Boxed.Mapping.Test/ImmutableMapper.cs, Tests/Boxed.Mapping.Test/ImmutableMapperTest.cs
Fixes https://github.com/Dotnet-Boxed/Framework/issues/237
=> Add Immutable Mappers

.github/workflows/build.yml
=> Add GitHub Actions Manual Execution

.editorconfig, Benchmarks/Boxed.Mapping.Benchmark/MapObjectBenchmark.cs, Directory.Build.props, Source/Boxed.AspNetCore.Swagger/OperationFilters/ClaimsOperationFilter.cs, Source/Boxed.AspNetCore.Swagger/OperationFilters/CorrelationIdOperationFilter.cs, Source/Boxed.AspNetCore.Swagger/OperationFilters/ForbiddenResponseOperationFilter.cs, Source/Boxed.AspNetCore.Swagger/OperationFilters/UnauthorizedResponseOperationFilter.cs, Source/Boxed.AspNetCore.Swagger/SchemaFilters/JsonPatchDocumentSchemaFilter.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/Enums/OpenGraphAvailability.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/Enums/OpenGraphType.cs, Source/Boxed.AspNetCore.TagHelpers/Twitter/Enums/CardType.cs, Source/Boxed.AspNetCore.TagHelpers/Twitter/Enums/CardTypeExtensions.cs, Source/Boxed.AspNetCore/Cursor.cs, Source/Boxed.DotnetNewTest/ProcessExtensions.StartAsync.cs, Source/Boxed.DotnetNewTest/Project.cs, Source/Boxed.DotnetNewTest/TempDirectory.cs, Tests/Boxed.AspNetCore.TagHelpers.Test/TestData/TwitterCardAnswerKey.cs, Tests/Boxed.AspNetCore.TagHelpers.Test/VisibilityTagHelperTest.cs, Tests/Boxed.Mapping.Test/AsyncImmutableMapperTest.cs, Tests/Boxed.Mapping.Test/AsyncMapperTest.cs
=> Bump .editorconfig to 2.1.0

.github/workflows/build.yml
=> Fix download-artifact v2 Upgrade

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml
=> Add GitHub Actions Permissions

README.md
=> Add NuGet Package Download Count

Directory.Build.props, Documentation/Boxed.AspNetCore.Swagger.md, Documentation/Boxed.AspNetCore.TagHelpers.md, Documentation/Boxed.AspNetCore.md, Documentation/Boxed.DotnetNewTest.md, Documentation/Boxed.Mapping.md, README.md, Source/Boxed.AspNetCore.Swagger/Boxed.AspNetCore.Swagger.csproj, Source/Boxed.AspNetCore.TagHelpers/Boxed.AspNetCore.TagHelpers.csproj, Source/Boxed.AspNetCore/Boxed.AspNetCore.csproj, Source/Boxed.DotnetNewTest/Boxed.DotnetNewTest.csproj, Source/Boxed.Mapping/Boxed.Mapping.csproj, Source/Directory.Build.props
=> Split embedded NuGet package README.md

Benchmarks/Boxed.Mapping.Benchmark/MapListBenchmark.cs, Benchmarks/Boxed.Mapping.Benchmark/MapObjectBenchmark.cs, appveyor.yml
=> Upgrade Windows image to VS 2022

Documentation/Boxed.AspNetCore.TagHelpers.md
=> Fix Twitter Card Docs

.github/release-drafter-Boxed.AspNetCore.yml, .github/release-drafter-Boxed.DotnetNewTest.yml, .github/release-drafter-Boxed.Mapping.yml, Framework.sln, Source/Boxed.AspNetCore.Swagger/Boxed.AspNetCore.Swagger.csproj, Source/Boxed.AspNetCore.TagHelpers/Boxed.AspNetCore.TagHelpers.csproj, Source/Boxed.AspNetCore/Boxed.AspNetCore.csproj, Source/Boxed.DotnetNewTest/Boxed.DotnetNewTest.csproj, Source/Boxed.Mapping/Boxed.Mapping.csproj
Fixes https://github.com/Dotnet-Boxed/Framework/issues/170
=> Add release-drafter

.github/workflows/build.yml, .github/workflows/release-drafter.yml, Framework.sln, Tests/Directory.Build.props, build.cake, global.json
Fixes https://github.com/Dotnet-Boxed/Framework/issues/170
=> Bump .NET SDK, Publish Test Results & Release Drafter

Tests/Directory.Build.props
=> Remove unnecessary package

Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphBooksBook.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphBooksGenre.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphBusiness.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphPlace.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphProductItem.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphRestaurant.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphRestaurantMenu.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphRestaurantMenuItem.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Facebook/OpenGraphRestaurantMenuSection.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/OpenGraphMetadata.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Standard/OpenGraphMusicAlbum.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Standard/OpenGraphMusicPlaylist.cs, Source/Boxed.AspNetCore.TagHelpers/OpenGraph/ObjectTypes/Standard/OpenGraphMusicSong.cs, Source/Boxed.AspNetCore.TagHelpers/SubresourceIntegrityTagHelper.cs, Source/Boxed.AspNetCore.TagHelpers/Twitter/Cards/TwitterCardApp.cs, Source/Boxed.AspNetCore.TagHelpers/Twitter/Cards/TwitterCardPlayer.cs, Source/Boxed.AspNetCore.TagHelpers/Twitter/Cards/TwitterCardSummary.cs, Source/Boxed.AspNetCore/HttpContextExtensions.cs, Source/Directory.Build.props, global.json
=> Switch to DotNet.ReproducibleBuilds

.github/workflows/build.yml, build.cake
=> Fix junit output

Source/Boxed.AspNetCore.Swagger/OperationFilters/ClaimsOperationFilter.cs, Source/Boxed.AspNetCore/ServiceCollectionExtensions.cs, Source/Boxed.DotnetNewTest/AssemblyResolver.cs, Source/Boxed.DotnetNewTest/ConfigurationService.cs, Source/Boxed.DotnetNewTest/DirectoryExtensions.cs, Source/Boxed.DotnetNewTest/DotnetNew.cs
=> Use Static Lambdas for Performance

Source/Boxed.AspNetCore/ServiceCollectionExtensions.cs
=> Remove unused generic constraint

appveyor.yml
=> Fix appveyor to be schema compliant
